# -- 키 바인딩 -----------------------------------------------------------------

# prefix를 C-Space으로 변경
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# pane 이동 (vi 스타일: hjkl)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 마우스 토글
bind m set -g mouse \; display 'mouse #{?#{mouse},on,off}'
