# -- Key Bindings --------------------------------------------------------------

# Change prefix to C-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Pane navigation (vi style: hjkl)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Toggle mouse
bind m set -g mouse \; display 'mouse #{?#{mouse},on,off}'
